### PR TITLE
update potential talk from crownpku

### PR DESCRIPTION
**Pull request by crownpku**
update potential talk from crownpku

### CODE REVIEW

**Comment by windmemory** [comment]
Great!
@crownpku welcome to Bot 5 Club!

Before I can merge this change, please sign the CLA above, then I can approve this PR and merge it.

**Comment by crownpku** [comment]
> Great!
> @crownpku welcome to Bot 5 Club!
> 
> Before I can merge this change, please sign the CLA above, then I can approve this PR and merge it.

CLA signed. Thank you!

**Comment by windmemory** [comment]
Seems like there are some format issues in the CI build, here are the logs:

```shell
docs/_people/crownpku.md: 11: MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/_people/crownpku.md: 12: MD034/no-bare-urls Bare URL used [Context: "http://www.crownpku.com"]
docs/_people/crownpku.md: 13: MD034/no-bare-urls Bare URL used [Context: "https://github.com/crownpku"]
docs/_people/crownpku.md: 14: MD034/no-bare-urls Bare URL used [Context: "https://www.linkedin.com/in/cr..."]
```

@crownpku could you please fix these issues?

**Comment by crownpku** [comment]
> Seems like there are some format issues in the CI build, here are the logs:
> 
> ```shell
> docs/_people/crownpku.md: 11: MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
> docs/_people/crownpku.md: 12: MD034/no-bare-urls Bare URL used [Context: "http://www.crownpku.com"]
> docs/_people/crownpku.md: 13: MD034/no-bare-urls Bare URL used [Context: "https://github.com/crownpku"]
> docs/_people/crownpku.md: 14: MD034/no-bare-urls Bare URL used [Context: "https://www.linkedin.com/in/cr..."]
> ```
> 
> @crownpku could you please fix these issues?

Seems it passes CI check now?

**Comment by windmemory** [comment]
Yes! It passed the CI check!

**Pull request merged**
