### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by kylezhang**
fixed typo.

### CODE REVIEW

**Comment by windmemory** [comment]
@kylezhang Please sign the CLA so we can merge this Pull Request.

**Comment by huan** [comment]
The following problems need to be fixed:

```sh
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 29: MD029/ol-prefix Ordered list item prefix [Expected: 1; Actual: 2; Style: 1/2/3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 30: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 31: MD029/ol-prefix Ordered list item prefix [Expected: 2; Actual: 3; Style: 1/2/3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 32: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 33: MD029/ol-prefix Ordered list item prefix [Expected: 3; Actual: 4; Style: 1/2/3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 34: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 35: MD029/ol-prefix Ordered list item prefix [Expected: 4; Actual: 5; Style: 1/2/3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 36: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 37: MD029/ol-prefix Ordered list item prefix [Expected: 5; Actual: 6; Style: 1/2/3]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 39: MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 62: MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Video"]
docs/_posts/2020-05-29-seminar-minutes-2020-11.md: 101: MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- 主席：王创峰"]
```

**Comment by kylezhang** [comment]
The format is very strict.😭

**Comment by huan** [comment]
You did a fantastic fix, thank you for the efforts of publishing our meeting notes!

**Pull request merged**
