### PR TITLE
Alex's post for chatbot talk

### PR DESCRIPTION
**Pull request by alex2010**
Hi, I finished my post for chatbot talk.

### CODE REVIEW

**Comment by windmemory** [comment]
Hi @alex2010 , we need to make sure the PR passed the Travis CI build before we can merge it.

**Comment by lijiarui** [comment]
@alex2Alex   you can run
` npm run test  ` before commit the code and it may help you find why travis ci didn't  pass.

**Comment by windmemory** [comment]
Hi @alex2010 , your PR is still not passing the Travis CI build, please make sure it passes the CI.

**Comment by alex2010** [comment]
test

**Comment by qhduan** [comment]
LGTM

**Pull request merged**
